### ISSUE TITLE
Increase resolution of images.

### ISSUE THREAD

**Issue by vsantjr** [EndlessSora/DeceiveD#4]
Hello,
First of all, congrats for your nice work. I have trained DeceiveD/APA with my set which are formed by 128 x 128 images. I am wondering whether I can generate higher resolution images (1024 x 1024) with your GAN based on low resolution ones. When preparing the data, I ran something like:

```python dataset_tool.py --source=/path/to/image/folder --dest=/path/to/archive.zip   --width=128 --height=128 --max-images=100```

To train (stylegan2 for 1024 x 1024): 

```python train.py --outdir=./experiments --gpus=4 --data=/path/to/mydataset.zip    --mirror=1   --cfg=stylegan2 --aug=apa --with-dataaug=true```

Inference:

``` python generate.py --outdir=out --trunc=1 --seeds=1000-1199 --network=/path/to/checkpoint/pkl```

But after the inference, the output were 128 x 128 images (as the original ones).

Thus, can we use it for creating higher resolution images?

Thank you.

**Comment by EndlessSora** [comment]
Hi, thanks for your interest in our work. Please ensure the dataset preparation, model training and inference with the same resolution. This factor should be consistent. For a higher resolution, e.g., 1024 x 1024, you need to prepare the data with 1024 x 1024.

**Comment by vsantjr** [comment]
Thank you for your response. I will try it.

Best Regards.
